sudo: false

language: node_js

node_js:
  - "10"

script:
  - PUBLIC_URL=https://ecrofeg.github.io/movie-list npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
